name: Build and GitHub Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: Build Binaries
      run: |
        mkdir -p dist
        
        # Сборка под Linux
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/wallgo-linux-amd64 ./cmd/apiserver/main.go
        
        # Сборка под Windows
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o dist/wallgo-windows-amd64.exe ./cmd/apiserver/main.go
        
        # Сборка под macOS
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o dist/wallgo-darwin-amd64 ./cmd/apiserver/main.go

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          dist/wallgo-linux-amd64
          dist/wallgo-windows-amd64.exe
          dist/wallgo-darwin-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}